# Default values for restic-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/jacksgt/restic-k8s
  tag: "" # falls back to `Chart.appVersion` if unspecified
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

restic:
  config:
    # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
    RESTIC_REPOSITORY: ""
    RESTIC_PASSWORD: ""
    # more values to be passed as environment variables to restic
    # ...

  backup:
    schedule: "22 0 * * *"
    suspend: false
    dryRun: false

  forget:
    suspend: false
    # once a week
    schedule: "44 3 * * 2"
    # according to which policy snapshots should be retained
    keepPolicy:
      last: 0
      hourly: 0
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
      within: "30d"
    dryRun: false

  # When data associated to deleted snapshots should be deleted
  prune:
    # once a week
    schedule: "33 4 * * 2"
    suspend: false
    dryRun: false

  # Regularly check (some of) the data stored in the remote repository for errors
  # https://restic.readthedocs.io/en/stable/045_working_with_repos.html#checking-integrity-and-consistency
  check:
    # once a week
    schedule: "5 22 * * 1"
    suspend: false
    readDataSubset: "25%"

# runs a special deployment with restic inside that allows you to perform operations on the repository backend
# e.g. `kubectl exec -it deploy/restic-toolbox -- restic stats`
debugToolbox:
  enabled: false

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
